routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'indexController@index')->name('index');
Route::get('pricing', function(){
  return view('pricing');
});


Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/ads/data', 'AdminController@adsData')->name('admin.adsData');
    Route::get('/ads', 'AdminController@ad')->name('admin.ads');
    Route::get('/ads/active', 'AdminController@adActive')->name('admin.adActive');
    Route::get('/ads/suspend', 'AdminController@adSuspend')->name('admin.adSuspend');
    Route::get('/ads/featured', 'AdminController@Featured')->name('admin.featured');
    Route::get('/ads/unfeatured', 'AdminController@unFeatured')->name('admin.unfeatured');
    Route::get('/users/data', 'AdminController@userData')->name('admin.usersData');
    Route::get('/users', 'AdminController@user')->name('admin.users');
    Route::resource('/category', 'CategoryController');
    Route::put('/category', 'CategoryController@store');
    Route::get('/category/deleted/{id}', 'CategoryController@destroy')->name('delete');
    Route::resource('/pages', 'pageController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'cityController');
    Route::resource('/faqs', 'FaqController');


});


Route::get('details', function(){
  return view('details');
});
Route::get('/faqs', 'homecontroller@faqindex');

Route::get('adpost', function(){
  return view('adpost');
});

Route::resource('ads', 'AdController');
Route::get('ads/select/category','AdController@selectCategory')->name('selectCategory');

Route::get('myads/{status}','HomeController@myAds');
Route::get('like/{ad}/{action}', 'AdController@likeIt')->name('like');
Route::get('giveMeCities', 'cityController@ajaxCities')->name('giveMeCities');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/{id}', 'HomeController@updateProfile')->name('updateprofile');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = false;

    public function parentCategory(){
      return $this->belongsTo('App\Category','parent');
    }


    public function subCategories(){
      return $this->hasMany('App\Category', 'parent');
    }

    public function ads(){
        return $this->hasMany('App\Ad');
    }


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Category;
use Auth;
use Illuminate\Http\Request;
class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
//        $this->middleware(function ($request, $next) {
//            $user = Auth::user()->projects;
//            return $next($request);
//        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $user= Auth::User();
        $categories= Category::with([
            'subCategories' => function($query){
                $query->select('id', 'name', 'parent');
            }
        ])->select('id', 'name','fa_icon')->where('parent',0)->get();
        return view('admin/category/index',compact('user','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();

        $categories = Category::where('parent', 0)->get();
        return view('admin.category.create', compact('categories','user'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'unique:categories|max:64|required',
            'fa_icon' => 'required|max:64',
            'parent' => 'required|max:64',
        ]);

        $category = new Category;
        $category->name = $request->name;
        $category->fa_icon = $request->icon;
        $category->parent = $request->parent;
        $category->save();



        return redirect()->back();
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $user=Auth::User();
        $categories = Category::where('parent', 0)->get();
        return view('admin.category.edit',compact('category','categories','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $validatedData = $request->validate([
            'name' => 'max:64|required|unique:categories,name',$category->id,
            'fa_icon' => 'required|max:64',
            'parent' => 'required|max:64',
        ]);
        $category->name = $request->name;
        $category->fa_icon = $request->icon;
        $category->parent = $request->parent;
        $category->save();
        return redirect(route('category.index'))->with(['update'=>'Category successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect(route('category.index'))->with(['deleted'=>'Category successfully updated.']);
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new Category</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('category.store')}}">
                                    {{csrf_field()}}
                                    <div class="box-body">
                                        <div class="form-group">

                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Category Name" required="required" value="">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Icon</label>
                                            <select class="js-source-states">
                                                <i class="fas fa-home"></i>
                                                <option value="fa-car" data-icon="fa-car">Car</option>
                                                <option value="fa-desktop" data-icon="fa-desktop">Electronics</option>
                                                <option value="fa-motorcycle" data-icon="fa-motorcycle">Moter Bike</option>
                                                <option value="fa-home" data-icon="fa-home">Home</option>
                                                <option value="fa-futbol-o" data-icon="fa-futbol-o">Sports</option>
                                                <option value="fa-paw" data-icon="fa-paw">Animals</option>
                                                <option value="fa-gift" data-icon="fa-gift">Gifts</option>
                                                <option value="fa-female" data-icon="fa-female">Health & Care</option>
                                                <option value="fa-linode" data-icon="fa-linode">Other</option>
                                            </select>
                                            <select class="js-example-templating js-states form-control" name="icon">

                                            </select>
                                        </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"></label>
                                        <select class="form-control" id="exampleFormControlSelect1" name="parent">
                                            <option value="0">Parent</option>
                                            @foreach($categories as $cat)
                                                <option value={{$cat->id}}>{{$cat->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    </div>
                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Add">          </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
            </div>
        </section>
    </div>
    @section('page_level_style')

        <style>


        /* Optional Wrapper to help with Responsive Designs */
        .select2-wrapper {
        width: 300px;
        }
        /* Optional styling to the right */
        .select2-results .fa {
        float: right;
        position: relative;
        line-height: 20px;
        }
        </style>
        @endsection
@section('page_level_script')

    <script type="text/javascript">
        $(document).ready(function() {
            // Initialize "states" example
            var $states = $(".js-source-states");
            var statesOptions = $states.html();
            $states.remove();

            $(".js-states").append(statesOptions);
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        function formatState (state) {
            if (!state.id) {
                return state.text;
            }

            var $state = $(
                '<span><i class="fa '+ state.element.dataset.icon.toLowerCase() +'" aria-hidden="true"></i> ' + state.text + '</span>'
            );
            return $state;
        };

        $(".js-example-templating").select2({
            templateResult: formatState
        }).addClass("form-control");
    </script>
@endsection
@stop

resources/views/admin/category/edit.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new Category</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('category.update',$category->id)}}">

                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="PUT">
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Category Name" required="required" value="{{$category->name}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Icon</label>
                                            <select class="js-source-states">
                                                    <option value="fa-car" data-icon="fa-car" {{$category->fa_icon == 'fa-car' ? 'selected':'' }}>Car</option>
                                                    <option value="fa-desktop" data-icon="fa-desktop" {{$category->fa_icon == 'fa-desktop' ? 'selected':'' }}>Electronics</option>
                                                    <option value="fa-motorcycle" data-icon="fa-motorcycle" {{$category->fa_icon == 'fa-motorcycle' ? 'selected':'' }}>Moter Bike</option>
                                                    <option value="fa-home" data-icon="fa-home" {{$category->fa_icon == 'fa-home' ? 'selected':'' }}>Home</option>
                                                    <option value="fa-futbol-o" data-icon="fa-futbol-o" {{$category->fa_icon == 'fa-futbol-o' ? 'selected':'' }}>Sports</option>
                                                    <option value="fa-paw" data-icon="fa-paw" {{$category->fa_icon == 'fa-paw' ? 'selected':'' }}>Animals</option>
                                                    <option value="fa-gift" data-icon="fa-gift" {{$category->fa_icon == 'fa-gift' ? 'selected':'' }}>Gifts</option>
                                                    <option value="fa-female" data-icon="fa-female" {{$category->fa_icon == 'fa-female' ? 'selected':'' }}>Health & Care</option>
                                                    <option value="fa-linode" data-icon="fa-linode" {{$category->fa_icon == 'fa-linode' ? 'selected':'' }}>Other</option>
                                            </select>
                                            <select class="js-example-templating js-states form-control" name="icon">
                                            </select>
                                            {{--<input type="text" class="form-control" name="icon" placeholder="Icon" required="required" value="{{$category->fa_icon}}">--}}
                                        </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"></label>
                                        <select class="form-control" id="exampleFormControlSelect1" name="parent">
                                            <option value="0">Parent</option>
                                            @foreach($categories as $cat)
                                                @if($cat->id == $category->parent)
                                                <option value="{{$cat->id}}" selected="selected">{{$cat->name}} </option>
                                                @else
                                                    <option value="{{$cat->id}}">{{$cat->name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                    </div>
                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Update"> </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
            </div>
        </section>
    </div>
@section('page_level_style')

    <style>


        /* Optional Wrapper to help with Responsive Designs */
        .select2-wrapper {
            width: 300px;
        }
        /* Optional styling to the right */
        .select2-results .fa {
            float: right;
            position: relative;
            line-height: 20px;
        }
    </style>
@endsection
@section('page_level_script')

    <script type="text/javascript">
        $(document).ready(function() {
            // Initialize "states" example
            var $states = $(".js-source-states");
            var statesOptions = $states.html();
            $states.remove();

            $(".js-states").append(statesOptions);
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        function formatState (state) {
            if (!state.id) {
                return state.text;
            }

            var $state = $(
                '<span><i class="fa '+ state.element.dataset.icon.toLowerCase() +'" aria-hidden="true"></i> ' + state.text + '</span>'
            );
            return $state;
        };

        $(".js-example-templating").select2({
            templateResult: formatState
        }).addClass("form-control");
    </script>
@endsection
@stop

resources/views/admin/category/index.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>

                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">All Categories</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->

                                    <div class="box-body">

                                        @if(Session::has('message'))
                                        <div class="alert alert-{{Session::has('message') ? 'success':'danger'}} alert-dismissible">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                            <h4><i class="icon fa fa-info"></i> Success!</h4>
                                            {{Session::get(message)}}
                                        </div>
                                        @endif



                                        <table id="users_data" class="table table-bordered table-striped">
                                            <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Icon</th>
                                                <th>Action</th>

                                            </tr>
                                            </thead>

                                            @foreach($categories as $category)
                                                <tr>
                                                <td>{{$category->name}}</td>
                                                <td><i class="fa {{$category->fa_icon}}" style="font-size:42px;"></i></td>
                                                   <td><a href="{{ route('category.edit', $category->id) }}"><button class="btn btn-warning btnSuspend" data-id="1">Update</button></a> | <input type="submit" class="btn btn-warning btnSuspend" onclick="frmdlt{{$category->id}}.submit();" >
                                                       <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$category->id}}" action="{{ route('category.destroy', $category->id)}}" method="post">
                                                           {!! method_field('delete') !!}
                                                           {{csrf_field()}}

                                                       </form> </td>
                                                </tr>

                                            @endforeach
                                        </table>
                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">

                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop