routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'indexController@index')->name('index');
Route::get('pricing', function(){
  return view('pricing');
});


Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/ads/data', 'AdminController@adsData')->name('admin.adsData');
    Route::get('/ads', 'AdminController@ad')->name('admin.ads');
    Route::get('/ads/active', 'AdminController@adActive')->name('admin.adActive');
    Route::get('/ads/suspend', 'AdminController@adSuspend')->name('admin.adSuspend');
    Route::get('/ads/featured', 'AdminController@Featured')->name('admin.featured');
    Route::get('/ads/unfeatured', 'AdminController@unFeatured')->name('admin.unfeatured');
    Route::get('/users/data', 'AdminController@userData')->name('admin.usersData');
    Route::get('/users', 'AdminController@user')->name('admin.users');
    Route::resource('/category', 'CategoryController');
    Route::put('/category', 'CategoryController@store');
    Route::get('/category/deleted/{id}', 'CategoryController@destroy')->name('delete');
    Route::resource('/pages', 'pageController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'cityController');
    Route::resource('/faqs', 'FaqController');


});


Route::get('details', function(){
  return view('details');
});
Route::get('/faqs', 'homecontroller@faqindex');

Route::get('adpost', function(){
  return view('adpost');
});

Route::resource('ads', 'AdController');
Route::get('ads/select/category','AdController@selectCategory')->name('selectCategory');

Route::get('myads/{status}','HomeController@myAds');
Route::get('like/{ad}/{action}', 'AdController@likeIt')->name('like');
Route::get('giveMeCities', 'cityController@ajaxCities')->name('giveMeCities');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/{id}', 'HomeController@updateProfile')->name('updateprofile');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public function state(){
      return $this->belongsTo('App\State');
    }
}

app/Http/Controllers/cityController.php
<?php
namespace App\Http\Controllers;
use App\City;
use Illuminate\Http\Request;
use Auth;
use App\State;
class cityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=Auth::User();
        $cities=City::with('state')->get();
        return view('admin.city.index',compact('user','cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();
        $states = State::all();
        return view('admin.city.create', compact('states','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $city = new City;
        $city->name = $request->name;
        $city->state_id = $request->state;
        $city->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
      $user=Auth::User();
        $states=State::all();
      return view('admin.city.edit',compact('user','city','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        $city->name = $request->name;
        $city->state_id=$request->state;
        $city->save();
        return redirect(route('city.index'))->with(['update'=>'City successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city->delete();
        return redirect(route('city.index'))->with(['deleted'=>'City successfully Deleted.']);
    }

    public function ajaxCities(Request $request){
      $cities = City::where('state_id', $request->id)->get();
      $str = '';
      foreach ($cities as $city) {
        $str.="<option value='$city->id'>$city->name</option>";
      }
        return $str;
    }
}

resources/views/admin/city/create.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new Category</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('city.store')}}">
                                    {{csrf_field()}}
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Category Name" required="required" value="">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"></label>
                                        <select class="form-control" id="exampleFormControlSelect1" name="state">

                                            @foreach($states as $state)
                                                <option value="{{$state->id}}">{{$state->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Add">          </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop

resources/views/admin/city/edit.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new Category</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('city.update',$city->id)}}">
                                    <input type="hidden" name="_method" value="PUT">
                                    {{csrf_field()}}
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="City Name" required="required" value="{{$city->name}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"></label>
                                        <select class="form-control" id="exampleFormControlSelect1" name="state">

                                            @foreach($states as $state)
                                                @if($state->id == $city->state_id)
                                                <option value="{{$state->id}}" selected="selected">{{$state->name}}</option>
                                                @else
                                                    <option value="{{$state->id}}">{{$state->name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Add">          </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop

resources/views/admin/city/index.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>

                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">All Categories</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->

                                    <div class="box-body">

                                        @if(Session::has('update'))
                                        <div class="alert alert-success alert-dismissible">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                            <h4><i class="icon fa fa-info"></i> Success!</h4>
                                            City updated Successfully
                                        </div>
                                        @endif
                                            @if(Session::has('deleted'))
                                                <div class="alert alert-success alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                                    <h4><i class="icon fa fa-info"></i> Success!</h4>
                                                    City deleted Successfully
                                                </div>
                                            @endif


                                        <table id="users_data" class="table table-bordered table-striped">
                                            <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>State</th>
                                                <th>Action</th>


                                            </tr>
                                            </thead>

                                            @foreach($cities as $city)
                                                <tr>
                                                <td>{{$city->name}}</td>
                                                <td>{{$city->state->name}}</td>
                                                   <td><a href="{{ route('city.edit', $city->id) }}"><button class="btn btn-warning btnSuspend" data-id="1">Update</button></a> | <input type="submit" class="btn btn-warning btnSuspend" onclick="frmdlt{{$city->id}}.submit();" >
                                                       <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$city->id}}" action="{{ route('city.destroy', $city->id)}}" method="post">
                                                           {!! method_field('delete') !!}
                                                           {{csrf_field()}}

                                                       </form> </td>
                                                </tr>

                                            @endforeach
                                        </table>
                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">

                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop