routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'indexController@index')->name('index');
Route::get('pricing', function(){
  return view('pricing');
});


Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/ads/data', 'AdminController@adsData')->name('admin.adsData');
    Route::get('/ads', 'AdminController@ad')->name('admin.ads');
    Route::get('/ads/active', 'AdminController@adActive')->name('admin.adActive');
    Route::get('/ads/suspend', 'AdminController@adSuspend')->name('admin.adSuspend');
    Route::get('/ads/featured', 'AdminController@Featured')->name('admin.featured');
    Route::get('/ads/unfeatured', 'AdminController@unFeatured')->name('admin.unfeatured');
    Route::get('/users/data', 'AdminController@userData')->name('admin.usersData');
    Route::get('/users', 'AdminController@user')->name('admin.users');
    Route::resource('/category', 'CategoryController');
    Route::put('/category', 'CategoryController@store');
    Route::get('/category/deleted/{id}', 'CategoryController@destroy')->name('delete');
    Route::resource('/pages', 'pageController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'cityController');
    Route::resource('/faqs', 'FaqController');


});


Route::get('details', function(){
  return view('details');
});
Route::get('/faqs', 'homecontroller@faqindex');

Route::get('adpost', function(){
  return view('adpost');
});

Route::resource('ads', 'AdController');
Route::get('ads/select/category','AdController@selectCategory')->name('selectCategory');

Route::get('myads/{status}','HomeController@myAds');
Route::get('like/{ad}/{action}', 'AdController@likeIt')->name('like');
Route::get('giveMeCities', 'cityController@ajaxCities')->name('giveMeCities');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/{id}', 'HomeController@updateProfile')->name('updateprofile');

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model{

    public function cities(){
      return $this->hasMany('App\City');
    }
}

app/Http/Controllers/stateController.php
<?php

namespace App\Http\Controllers;
use Auth;
use App\State;
use Illuminate\Http\Request;

class stateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=Auth::User();
        $state=State::all();
        return view('admin.state.index',compact('user','state'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();
        return view('admin.state.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $state = new State;
        $state->name = $request->name;
        $state->save();



        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function show(State $state)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function edit(State $state)
    {
        $user=Auth::User();

        return view('admin.state.edit',compact('user','state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, State $state)
    {
        $state->name = $request->name;
        $state->save();
        return redirect(route('states.index'))->with(['update'=>'State successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(State $state)
    {
        $state->delete();
        return redirect(route('states.index'))->with(['deleted'=>'State successfully updated.']);
    }
}

resources/views/admin/state/create.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new State</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('states.store')}}">
                                    {{csrf_field()}}
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">State Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Category Name" required="required" value="">
                                        </div>

                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Add">          </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop

resources/views/admin/state/edit.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </section>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Add new State</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" method="post" action="{{route('states.update',$state->id)}}">
                                    <input type="hidden" name="_method" value="PUT">
                                    {{csrf_field()}}
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">State Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Category Name" required="required" value="{{$state->name}}">
                                        </div>

                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">
                                        <input type="submit" class="btn btn-primary" name="btnsubmit" value="Add">          </div>
                                </form>
                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop

resources/views/admin/state/index.blade.php
@extends('admin.theme.master')
@section('content')
    <div class="content-wrapper" style="min-height: 916px;">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>

                    <div class="row">
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">All States</h3>
                                </div>
                                <!-- /.box-header -->
                                <!-- form start -->

                                    <div class="box-body">

                                        @if(Session::has('update'))
                                        <div class="alert alert-success alert-dismissible">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                            <h4><i class="icon fa fa-info"></i> Success!</h4>
                                            State updated Successfully
                                        </div>
                                        @endif
                                            @if(Session::has('deleted'))
                                                <div class="alert alert-success alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                                    <h4><i class="icon fa fa-info"></i> Success!</h4>
                                                    State deleted Successfully
                                                </div>
                                            @endif


                                        <table id="users_data" class="table table-bordered table-striped">
                                            <thead>
                                            <tr>
                                                <th>Name</th>

                                                <th>Action</th>


                                            </tr>
                                            </thead>

                                            @foreach($state as $states)
                                                <tr>
                                                <td>{{$states->name}}</td>

                                                   <td><a href="{{ route('states.edit', $states->id) }}"><button class="btn btn-warning btnSuspend" data-id="1">Update</button></a> | <input type="submit" class="btn btn-warning btnSuspend" onclick="frmdlt{{$states->id}}.submit();" >
                                                       <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$states->id}}" action="{{ route('states.destroy', $states->id)}}" method="post">
                                                           {!! method_field('delete') !!}
                                                           {{csrf_field()}}

                                                       </form> </td>
                                                </tr>

                                            @endforeach
                                        </table>
                                    </div>

                                    <!-- /.box-body -->
                                    <div class="box-footer">

                            </div>
                            <!-- /.box -->
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
        </section>
    </div>

@stop