routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'indexController@index')->name('index');
Route::get('pricing', function(){
  return view('pricing');
});


Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/ads/data', 'AdminController@adsData')->name('admin.adsData');
    Route::get('/ads', 'AdminController@ad')->name('admin.ads');
    Route::get('/ads/active', 'AdminController@adActive')->name('admin.adActive');
    Route::get('/ads/suspend', 'AdminController@adSuspend')->name('admin.adSuspend');
    Route::get('/ads/featured', 'AdminController@Featured')->name('admin.featured');
    Route::get('/ads/unfeatured', 'AdminController@unFeatured')->name('admin.unfeatured');
    Route::get('/users/data', 'AdminController@userData')->name('admin.usersData');
    Route::get('/users', 'AdminController@user')->name('admin.users');
    Route::resource('/category', 'CategoryController');
    Route::put('/category', 'CategoryController@store');
    Route::get('/category/deleted/{id}', 'CategoryController@destroy')->name('delete');
    Route::resource('/pages', 'pageController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'cityController');
    Route::resource('/faqs', 'FaqController');


});


Route::get('details', function(){
  return view('details');
});
Route::get('/faqs', 'homecontroller@faqindex');

Route::get('adpost', function(){
  return view('adpost');
});

Route::resource('ads', 'AdController');
Route::get('ads/select/category','AdController@selectCategory')->name('selectCategory');

Route::get('myads/{status}','HomeController@myAds');
Route::get('like/{ad}/{action}', 'AdController@likeIt')->name('like');
Route::get('giveMeCities', 'cityController@ajaxCities')->name('giveMeCities');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/{id}', 'HomeController@updateProfile')->name('updateprofile');

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    //
}

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\Faq;
use Illuminate\Http\Request;
use Auth;
class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user= Auth::User();
        $faqs=Faq::all();
        return view('admin.faqs.index',compact('faqs','user'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();
        return view('admin.faqs.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $faq = new Faq;
        $faq->title = $request->title;
        $faq->content = $request->content;
        $faq->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function show(Faq $faq)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function edit(Faq $faq)
    {
        $user=Auth::User();

        return view('admin.faqs.edit',compact('user','faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Faq $faq)
    {
        $faq->title = $request->title;
        $faq->content=$request->content;
        $faq->save();
        return redirect(route('faqs.index'))->with(['update'=>'FAQ successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function destroy(Faq $faq)
    {

        $faq->delete();
        return redirect(route('faqs.index'))->with(['deleted'=>'FAQ successfully Deleted.']);

    }
}

resources/views/admin/faqs/create.blade.php
@extends('admin.theme.master')
@section('content')

    <div class="content-wrapper" style="min-height: 901px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>


                <div class="accordion">
                    <div class="col-xs-12">

                    <div class="panel-group" id="accordion">
<form class="" action="{{route('faqs.store')}}" method="post">
    {{csrf_field()}}
                        <div class="panel panel-default panel-faq">
                            <div class="panel-heading active-faq">
                                        <input type="text" name="title" class="form-control" placeholder="FAQ TITLE">

                            </div><!-- panel-heading -->

                            <div id="faq-one" class="panel-collapse collapse collapse in">
                                <div class="panel-body">
                                    <textarea class="form-control" name="content"></textarea>

                                <div class="col-xs-12"><br>
                        <!-- panel -->
                                <button type="submit" class="btn btn-primary">Create Your FAQ</button>
                                </div>
</form>
                        </div>
                        </div>
                        </div>
                    </div>
                </div>
                </div>

@stop

resources/views/admin/faqs/edit.blade.php
@extends('admin.theme.master')
@section('content')

    <div class="content-wrapper" style="min-height: 901px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>


        <div class="accordion">
            <div class="col-xs-12">

                <div class="panel-group" id="accordion">
                    <form class="" action="{{route('faqs.update',$faq->id)}}" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        {{csrf_field()}}
                        <div class="panel panel-default panel-faq">
                            <div class="panel-heading active-faq">
                                <input type="text" name="title" class="form-control" value="{{$faq->title}}">

                            </div><!-- panel-heading -->

                            <div id="faq-one" class="panel-collapse collapse collapse in">
                                <div class="panel-body">
                                    <textarea class="form-control" name="content">{{$faq->content}}</textarea>

                                    <div class="col-xs-12"><br>
                                        <!-- panel -->
                                        <button type="submit" class="btn btn-primary">Create Your FAQ</button>
                                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

@stop

resources/views/admin/faqs/index.blade.php
@extends('trade.master')
@section('content')
    <section id="main" class="clearfix page">
        <div class="container">
            <div class="faq-page">
                <div class="breadcrumb-section">
                    <!-- breadcrumb -->
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li>FAQ</li>
                    </ol><!-- breadcrumb -->
                    <h2 class="title">Trade ads FAQ</h2>
                </div>

                <div class="accordion">
                    <div class="panel-group" id="accordion">
                        @if(Session::has('update'))
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-info"></i> Success!</h4>
                                FAQ updated Successfully
                            </div>
                        @endif
                        @if(Session::has('deleted'))
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-info"></i> Success!</h4>
                                FAQ deleted Successfully
                            </div>
                        @endif
                        <div class="panel panel-default panel-faq">
                            @foreach($faqs as $faq)
                                <div class="panel-heading active-faq">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#faq-one">
                                        <h4 class="panel-title">
                                            {{$faq->title}}
                                            <span class="pull-right"><i class="fa fa-minus"></i></span>
                                        </h4>
                                    </a>
                                </div><!-- panel-heading -->

                                <div id="faq-one" class="panel-collapse collapse collapse in">
                                    <div class="panel-body">
                                        <p>{{$faq->content}}</p>
                                        <p><a href="{{route('faqs.edit',$faq->id)}}"><button class="btn btn-warning btnSuspend" data-id="1">EDIT</button></a> |<input type="submit" class="btn btn-warning btnSuspend" onclick="frmdlt{{$faq->id}}.submit();" >
                                        <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$faq->id}}" action="{{ route('faqs.destroy', $faq->id)}}" method="post">
                                            {!! method_field('delete') !!}
                                            {{csrf_field()}}

                                        </form>  </p>
                                    </div>
                                </div>
                        </div><!-- panel -->

                        @endforeach
                    </div>
                </div>

            </div><!-- faq-page -->
        </div><!-- container -->
        <section id="something-sell" class="clearfix parallax-section">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h2 class="title">Did Not find your answer yet? Still need help ?</h2>
                        <h4>Send us a note to Help Center</h4>
                        <a href="contact-us.html" class="btn btn-primary">Contact Us</a>
                    </div>
                </div><!-- row -->
            </div><!-- contaioner -->
        </section><!-- something-sell -->
    </section>
@stop